### GetAllCommands()

GET http://localhost:5000/api/commands HTTP/1.1

### GetCommandById()

GET http://localhost:5000/api/commands/3 HTTP/1.1

### CreateCommand()

POST http://localhost:5000/api/commands HTTP/1.1
content-type: application/json

{
    "howTo": "Build a .NET Core App",
    "platform": ".NET Core CLI",
    "commandLine": "dotnet build"
}